name: Go CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with: {go-version: '1.22'}
    - run: go test ./...
    - run: go vet ./...
    - run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    - run: golangci-lint run 